### ISSUE TITLE
Module hanging Chataigne

### ISSUE THREAD

**Issue by gavspav** [zak-45/WLEDAudioSync-Chataigne-Module#1]
Not sure if it's user error but when I load the moduie in chataigne it hangs - spinning beach ball.

I have a 2020 14" macbook Pro, M1, 14.2. I've tried it with both the latest stable and beta releases of Chataigne.

Any ideas? Thanks.

**Comment by zak-45** [comment]
Hi, already seen similar problem with another Chataigne Module. Do you  have tested with version 1.9.17. I know that Chataigne sometimes made some breaking changes when version upgrade.

**Comment by zak-45** [comment]
Closing had no more info....
