### ISSUE TITLE
Not getting any connection to wled

### ISSUE THREAD

**Issue by Robiroboter33** [zak-45/WLEDAudioSync-Chataigne-Module#2]
I’ve tried multiple times to establish a working connection, but my LEDs remain off.
Using WledSRServer, I can sync my LEDs to music without any issues, so I’m confident there are no network or firewall problems.

I use a ESP8266 setup with now  WLED v0.15.0-b6 installed, the latest moonmodules version does also not work.

I’m not sure where the issue lies. I’ve also managed to get a working connection using other WLED modules in Chataigne, like the WLED-Chataigne-Module, so Chataigne itself seems to be functioning correctly.
I also tried the same stuff on another Laptop, but this doesn´t change anything.

Has anyone else experienced similar issues and knows how to fix them?

I really want to get this working but have run out of ideas.

What additional information do you need from me to help solve the problem?

Thank you so much! :)

**Comment by zak-45** [comment]
For esp8266, message type need to be v1 

![image](https://github.com/user-attachments/assets/cec0e92a-5808-4e71-841a-4b6247c3fa32)

Be sure to be on the same VLAN as your WLED device after that,  you can click on "Send test message" to force to join the multicast group.


and yout need to have the right WLED fw (the one with 160):

![image](https://github.com/user-attachments/assets/7210137e-0a36-46f5-94d4-1ae7494efe32)

**Comment by zak-45** [comment]
Ooops, message v2 work also with the new fw

**Comment by Robiroboter33** [comment]
Thank you for your fast anwer :)
It still doesnt work and I dont know, what I´m doing wrong.

This is my WLED Version:
![image](https://github.com/user-attachments/assets/dce101b3-a511-429d-aaf5-3ba045f841ac)

I changed the UTP Port to 11988 and did a reboot, those are my sync settings, with the original port it also doesnt work:

![image](https://github.com/user-attachments/assets/8dd23ddd-bfb4-450f-9159-c45a8e8df1ab)

![image](https://github.com/user-attachments/assets/3270470e-6c16-44bb-ba04-bddca4c45d45)

Is there maybe an issue with my settings?

I tried the test message sending feature, but I dont get any answer.
Those are my chataigne settings, V2 doesn´t work either.

![image](https://github.com/user-attachments/assets/e5eee41b-ad8a-49bc-a69f-1f4c40c5c342)

Should I just buy an ESP32 and solder the wires again? Or are there any other things I can try?

Thank you very much :)

**Comment by zak-45** [comment]
This should work on esp8266... work at home... even if 8266 support will be drop down soon.

But, looks like you do not use the right fw...your CPU clock is 80Mhz

try this one : https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b7/WLED_0.15.0-b7_ESP8266_160.bin
that's the last one with 160Mhz

This will overclock your esp8266, so be sure you can access it easly, some esp8266 do not support it. In case of no booting, you will need to upload another fw via serial. On my side, do not had to face to such issue on any of my esp8266: got 6 of them.

**Comment by Robiroboter33** [comment]
Thank you again!

I now have a connection, as the "Receive Mode" in the Info Panel of the WLED GUI updates to the receive mode v1 / v2 I select in the web server. Additionally, my LEDs no longer flash randomly as they did before when there was no connection. However, now the LED strip stays completely dark. Neither of the test buttons has any effect, and the LEDs also do not respond to music.

Are there any effect settings or known issues that could help fix this?

Thank you very much!

**Comment by zak-45** [comment]
Now, you need to be sure that you have followed all pre-request: sound card settings (audio loopbac), be on the same VLAN etc... take a look here :  https://www.youtube.com/watch?v=Fy8NGl8-Jyc

**Comment by zak-45** [comment]
and to check LAN issue : https://github.com/zak-45/WLEDAudioSyncMCast

**Comment by Robiroboter33** [comment]
I already watched the video and applied the suggested settings, but they didn’t work.

Regarding the LAN issue fix, which IP address should I use with this command?

WLEDAudioSyncMCast-Windows.exe --ip 192.168.1.12 --group 239.0.0.1 --port 19890

I used "netsh interface ip show joins" but dont know, which one to coose.

![image](https://github.com/user-attachments/assets/ea07e67c-969a-4f95-b184-6ac6f4610b6d)


The --group parameter can stay at 239.0.0.1 ?

And the --port parameter is the one in the example 19890 or do i have to choose another one?

**Comment by zak-45** [comment]
Ok, I do not know your network config, you should. 
So... let me do it by example: 

PC ip : 192.168.1.10
WLED ip : 192.168.1.20
Multicast group : 239.0.0.1
Port : 11988

As you can see, PC and WLED are on the same VLAN : 192.168.1.xxx (xxx=1...254)
------- > If this is not the case, change PC ip or WLED ip.....

if you use default port: 11988 and you want to join multicast group 239.0.0.1 

WLEDAudioSyncMCast-Windows.exe --ip 192.168.1.10 --group 239.0.0.1 --port 11988

The WLED device need to use port : 11988 

N.B. : All of this should be done in automatic way when all settings done,  here only FYI

![image](https://github.com/user-attachments/assets/b3e23dc7-33cb-4463-aa12-528e172dd498)

**Comment by Robiroboter33** [comment]
Thank you again for all your help, but I think I’m giving up on this.

Both devices are in the same VLAN.

I tried the commands on both my laptop and desktop PC, and I suspect the issue is related to my router’s port forwarding.
I attempted to forward the UDP ports, but it didn’t make any difference.

What’s strange is that music sync still works with the default settings on "WledSRServer-v1.1.1", even though port forwarding issues should exist there as well.

These are the only settings, I can change.

![image](https://github.com/user-attachments/assets/bae4e280-0545-4edb-85c3-3aba5604260f)


I’m out of ideas and feeling a bit disappointed, but I’m hoping it will work with new ESP32 controllers.

Do you have any final suggestions?

Thank you again for your quick and helpful support!

**Comment by zak-45** [comment]
Ok, not so helpful support as this not work :(
I see you're on windows, so the portable version should be Ok for you. Do not change any default settings....
If you take a look to the WledSRServer, the SR port is also by default to : 11988
If this one work WLEDAudioSync should also ...
Be sure to have set audio in the right way, mean that when you click on test, you should ear a sound and see FFT data.

Hummm .. and with these settings, you could not have both running on same time !

**Comment by Robiroboter33** [comment]
Thanks again, I got a final idea and analyzed the signals sent from my PC with wireshark. This is one example package from the working WledSRServer:

![image](https://github.com/user-attachments/assets/716a9391-bc0c-4f87-af65-7ce0d069b41d)


And this is a package sent from chataigne, which doesnt light up any LEDs:

![image](https://github.com/user-attachments/assets/9766d836-8ee3-45ef-9cf3-1f76d6bf009d)


I´m a little confused, because the chataigne package has double the size, its 88 bytes, the one from SRS is just 44 bytes. Is the size an issue?
Furthermore the SRS sends data, whereas the chataigne one got many zeros, while playing music. I think this is the issue. 

SRS Data:

![image](https://github.com/user-attachments/assets/743eeb7c-14dd-4386-b169-435ec8258ae5)


Chataigne Data:

![image](https://github.com/user-attachments/assets/ef17b42c-c726-49fa-b303-e5db5910dfee)

If I hit the send test message button, this is the result from wireshark:

![image](https://github.com/user-attachments/assets/e8d30a98-a441-4fc3-99f2-d07558b91a86)

Just 21 bytes large, but containing data at least.

Hitting and hearing the test audio button changes nothing in the data stream.

Are you into those data streams?

**Comment by Robiroboter33** [comment]
Okay, there must be something wrong with my sound card module, im playing with the command tester some music directly from my pc and I dont get any data content in the packages.

![image](https://github.com/user-attachments/assets/8095ee49-bbf1-49ff-aa02-fe0515d46e99)
 Is there something completely wrong? Sorry for the spam, I just really want to get it running :D

**Comment by zak-45** [comment]
Be sure to test the same message version (44bytes : V2 if I'm not wrong)
The zero data show that problem come from audio source... Chataigne do not grab any sound data for any reason !!??

**Comment by zak-45** [comment]
yep, audio settings, you need to use the loopback if got one, see the audio part of the main doc.

**Comment by zak-45** [comment]
FYI: If you use some 'digital' output, the windows Mixer will not be able to work a this work only with 'analog'. 
In this case, you need a tool like 'Voicemeeter' or similar.

**Comment by zak-45** [comment]
I will close it. Feel free to open a new one in case of any issue.
